baseURL = "http://localhost"
title = "archivekeep"
theme = "hugo-book"

disableKinds = ['taxonomy', 'term']

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
guessSyntax = true
style = 'tango'

[params]
BookTheme = 'auto'
BookSearch = false
BookSection = '*'
BookRepo = 'https://github.com/archivekeep/archivekeep'


[menu]

[[menu.after]]
name = "GitHub"
url = "https://github.com/archivekeep/archivekeep"
weight = 10



[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]
