name: Go

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install
        run: go install golang.org/x/tools/cmd/goimports@v0.1.12

      - name: Format check
        run: ./bin/format_check.sh

      - name: Build
        run: go build -v ./...

      # TODO: fix unstable test
      # - name: Test
      #   run: go test -v ./...
      #
      # - name: Test (hardened)
      #   run: go test -race -count=10 -v ./...
