name: Go

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install tools
        run: go install golang.org/x/tools/cmd/goimports@v0.1.12

      - name: Install native dependencies
        run: |
          id -a
          sudo apt-get -y install gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev

      - name: Download dependencies
        run: go mod download -x

      - name: Run go vet check
        run: go vet ./...

      - name: Run format check
        run: ./bin/format_check.sh

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Test (race)
        run: go test -race -count=1 -v ./...

      - name: Test (stability)
        run: go test -count=12 -v ./...
